server:
  port: 8081

# 日志
logging:
  level:
    per.study.*: debug

spring:
  application:
    name: micro-weather-collection-server
  ## Redis
  redis:
    host: redis

eureka:
  client:
    service-url:
      default-zone: http://weather-eureka:8761/eureka/
