server:
  port: 8082

# 日志
logging:
  level:
    per.study.*: debug

spring:
  application:
    name: micro-weather-data-server
  ## Redis
  redis:
    host: redis

eureka:
  client:
    service-url:
      default-zone: http://weather-eureka:8761/eureka/