server:
  port: 8888

spring:
  application:
    name: micro-weather-gateway-zuul

eureka:
  client:
    service-url:
      default-zone: http://weather-eureka:8761/eureka/

zuul:
  routes:
    city:
      path: /city/**
      service-id: micro-weather-city-server
    data:
      path: /data/**
      service-id: micro-weather-data-server

