server:
  port: 9999

spring:
  application:
    name: micro-weather-config-server
  cloud:
    config:
      server:
        git:
#          uri: https://github.com/ybin1212/microservice-weather
          search-paths: config-repo

eureka:
  client:
    service-url:
      default-zone: http://weather-eureka:8761/eureka/
